In [1]:
import sys
print(sys.executable)

/home/tanushri/AgriVision-AI/venv/bin/python3

In [2]:
import pandas as pd

df = pd.read_csv("datasets/archive (1)/yield_df.csv")

print("Dataset Loaded Successfully")
print("Shape:", df.shape)

Dataset Loaded Successfully
Shape: (28242, 8)

In [3]:
print(df.columns)

Index(['Unnamed: 0', 'Area', 'Item', 'Year', 'hg/ha_yield',
       'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp'],
      dtype='str')

In [4]:
# Remove useless column
df = df.drop("Unnamed: 0", axis=1)

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Area                           28242 non-null  str
 1   Item                           28242 non-null  str
 2   Year                           28242 non-null  int64
 3   hg/ha_yield                    28242 non-null  int64
 4   average_rain_fall_mm_per_year  28242 non-null  float64
 5   pesticides_tonnes              28242 non-null  float64
 6   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(2), str(2)
memory usage: 1.5 MB
None

In [5]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 2310

In [6]:
df.describe()

,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
count,28242.000000,28242.000000,28242.00000,28242.000000,28242.000000
mean,2001.544296,77053.332094,1149.05598,37076.909344,20.542627
std,7.051905,84956.612897,709.81215,59958.784665,6.312051
min,1990.000000,50.000000,51.00000,0.040000,1.300000
25%,1995.000000,19919.250000,593.00000,1702.000000,16.702500
50%,2001.000000,38295.000000,1083.00000,17529.440000,21.510000
75%,2008.000000,104676.750000,1668.00000,48687.880000,26.000000
max,2013.000000,501412.000000,3240.00000,367778.000000,30.650000

In [7]:
print("Shape Before:", df.shape)

df = df.drop_duplicates()

print("Shape After:", df.shape)

Shape Before: (28242, 7)
Shape After: (25932, 7)

In [8]:
df.head()

,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

In [9]:
print("Unique Areas:", df["Area"].nunique())
print("Unique Crops:", df["Item"].nunique())

Unique Areas: 101
Unique Crops: 10

In [10]:
print(df["Item"].value_counts())

Item
Potatoes                3956
Maize                   3824
Wheat                   3539
Rice, paddy             3091
Soybeans                2940
Sorghum                 2770
Sweet potatoes          2593
Cassava                 1889
Yams                     774
Plantains and others     556
Name: count, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

area_encoder = LabelEncoder()
item_encoder = LabelEncoder()

df["Area"] = area_encoder.fit_transform(df["Area"])
df["Item"] = item_encoder.fit_transform(df["Item"])

print("Encoding Completed")

Encoding Completed

In [13]:
X = df.drop("hg/ha_yield", axis=1)
y = df["hg/ha_yield"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (25932, 6)
Target Shape: (25932,)

In [14]:
print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (25932, 6)
Target Shape: (25932,)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (20745, 6)
Testing Shape: (5187, 6)

In [16]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest Model Trained Successfully")

Random Forest Model Trained Successfully

In [17]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

y_pred = rf_model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R² Score :", r2)
print("MAE      :", mae)
print("RMSE     :", rmse)

R² Score : 0.9833057918295581
MAE      : 4221.719099672258
RMSE     : 10999.900083399647

In [18]:
import joblib

joblib.dump(rf_model, "models/yield_prediction_model.pkl")

print("Yield Prediction Model Saved")

Yield Prediction Model Saved

In [19]:
import joblib

joblib.dump(area_encoder, "models/area_encoder.pkl")
joblib.dump(item_encoder, "models/item_encoder.pkl")

print("Encoders Saved Successfully")

Encoders Saved Successfully